### ISSUE TITLE
Crash upon running on Arch Linux

### ISSUE THREAD

**Issue by Z-A-Y-D** [tranxuanthang/lrcget#140]
When I try running `lrcget` on Arch from the lrget-bin package in the AUR, it crashes with this:

```
** (lrcget:20341): WARNING **: 21:44:01.837: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
Database file path: /home/main/.local/share/net.lrclib.lrcget/db.sqlite3
Existing database version: 4
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
thread 'main' panicked at src/main.rs:450:34:
Failed to initialize audio player: The requested device is no longer available. For example, it has been unplugged.

Caused by:
    The requested device is no longer available. For example, it has been unplugged.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Someone in the #archlinux-aur IRC channel on Libera also had the above problem

>Show full backtrace
```
** (lrcget:40131): WARNING **: 21:56:33.951: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
Database file path: /home/main/.local/share/net.lrclib.lrcget/db.sqlite3
Existing database version: 4
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
thread 'main' panicked at src/main.rs:450:34:
Failed to initialize audio player: The requested device is no longer available. For example, it has been unplugged.

Caused by:
    The requested device is no longer available. For example, it has been unplugged.

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: __libc_start_main
  14: <unknown>
stack backtrace:
   0:     0x57645d3831c5 - <unknown>
   1:     0x57645d3ae80b - <unknown>
   2:     0x57645d37fa5f - <unknown>
   3:     0x57645d3844c1 - <unknown>
   4:     0x57645d38419c - <unknown>
   5:     0x57645d384b21 - <unknown>
   6:     0x57645d384987 - <unknown>
   7:     0x57645d383689 - <unknown>
   8:     0x57645d384614 - <unknown>
   9:     0x57645ca29a73 - <unknown>
  10:     0x57645ca29f46 - <unknown>
  11:     0x57645cb86f6e - <unknown>
  12:     0x57645cba2e58 - <unknown>
  13:     0x57645cbb56f4 - <unknown>
  14:     0x57645cba7745 - <unknown>
  15:     0x57645cd264d7 - <unknown>
  16:     0x57645cca68c0 - <unknown>
  17:     0x57645cb192f0 - <unknown>
  18:     0x57645caee003 - <unknown>
  19:     0x57645cbd2c39 - <unknown>
  20:     0x57645d377720 - <unknown>
  21:     0x57645cb193a5 - <unknown>
  22:     0x75d43b9f5e08 - <unknown>
  23:     0x75d43b9f5ecc - __libc_start_main
  24:     0x57645ca2a445 - <unknown>
  25:                0x0 - <unknown>
```

>Unofficial package

I also get this when running the Appimage in releases:
```
Cannot get default EGL display: EGL_SUCCESS
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
fish: Job 1, './lrcget_0.5.0_amd64.AppImage' terminated by signal SIGSEGV (Address boundary error)
```
>Compile from release
```
Error failed to bundle project: error running appimage.sh
```
>Compile from main
```
Error failed to bundle project: error running appimage.sh
```

I don't know Rust or Node so I have no idea what's going on here, any help would be appreciated.

**Comment by tranxuanthang** [comment]
The panick is caused by this line:

https://github.com/tranxuanthang/lrcget/blob/39b921bb5ea6a106414b178c579ffe5540cf07ee/src-tauri/src/main.rs#L450

I remember I handled the unwrap gracefully recently in a in-development branch but haven't pushed it to `main` yet. I'll look into it.

It might be caused by the lack of an audio device. For example, if you are trying to run it on a graphical server.

**Comment by Z-A-Y-D** [comment]
> The panick is caused by this line:
> 
> https://github.com/tranxuanthang/lrcget/blob/39b921bb5ea6a106414b178c579ffe5540cf07ee/src-tauri/src/main.rs#L450
> 
> I remember I handled the unwrap gracefully recently in a in-development branch but haven't pushed it to `main` yet. I'll look into it.
> 
> It might be caused by the lack of an audio device. For example, if you are trying to run it on a graphical server.

I'm not sure what "audio device" could mean here other than an audio output, but I do have my headphones plugged in. Please do let me know when it does get fixed though, I've been waiting for a while to get to use this with my library but never bothered to report the issue until now.

**Comment by tranxuanthang** [comment]
Another reason could be some packages are missing. Especially if you install Archlinux without a DE like Gnome or KDE Plasma, and only use a window manager like i3wm or awesomewm.

Can you check if you have `pipewire-alsa` installed? More information in this issue: https://github.com/tranxuanthang/lrcget/issues/54#issuecomment-2094284061

**Comment by Z-A-Y-D** [comment]
> Another reason could be some packages are missing. Especially if you install Archlinux without a DE like Gnome or KDE Plasma, and only use a window manager like i3wm or awesomewm.
> 
> Can you check if you have `pipewire-alsa` installed? More information in this issue: [#54 (comment)](https://github.com/tranxuanthang/lrcget/issues/54#issuecomment-2094284061)
> 
> If I "fixed" this, it only prevents crash at startup, you can still download and search for lyrics but cannot use the playback feature unfortunately, until you find out what you are missing.

pipewire-alsa was missing, just added it now.
Now the error is different, on the AUR package it's this:
```
** (lrcget:90109): WARNING **: 02:24:15.260: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
Database file path: /home/main/.local/share/net.lrclib.lrcget/db.sqlite3
Existing database version: 4
Gdk-Message: 02:24:15.489: Error 71 (Protocol error) dispatching to Wayland display.
```

And on the AppImage:
```
Cannot get default EGL display: EGL_SUCCESS
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
fish: Job 1, './lrcget_0.5.0_amd64.AppImage' terminated by signal SIGSEGV (Address boundary error)
```

Now that it's relevant, I'm on KDE Plasma (Wayland) 6.1.5

**Comment by tranxuanthang** [comment]
If you have an Nvidia GPU, there is an unfixed bug in upstream. Could you also try follow this? https://github.com/tranxuanthang/lrcget/issues/54#issuecomment-2094306594

**Comment by Z-A-Y-D** [comment]
> If you have an Nvidia GPU, there is an unfixed bug in upstream. Could you also try following this? [#54 (comment)](https://github.com/tranxuanthang/lrcget/issues/54#issuecomment-2094306594)

I do have an NVIDIA GPU, and the command you sent does open the window. If the audio player thing you mentioned before applies here, that doesn't matter that much to me, I'll probably just open them in mpv or ncmpcpp out of habit anyways.

Thanks for the help!

This probably warrants a whole new issue, but before I close, this doesn't seem to be recognizing my .ape files or even my .opus files. It does pick up .flacs though.

**Comment by tranxuanthang** [comment]
> This probably warrants a whole new issue, but before I close, this doesn't seem to be recognizing my .ape files or even my .opus files. It does pick up .flacs though.

LRCGET depends on other native Rust crates such as `lofty` for reading tags, `symphonia` and `cpal` for playback, and they don't have support for every audio extensions unfortunately.

Some other ways are embedding `mpv` and using `libmpv` to interact with it for example, and `vlc` with `libvlc` can be another choice, but these solutions have their own disadvantages.
