### ISSUE TITLE
LRCGET crashes with no user-facing error message when there is no default audio device

### ISSUE THREAD

**Issue by RansomTime** [tranxuanthang/lrcget#157]
On Windows, when launching LRCGET, if there is no default audio device, LRCGET will crash and close without providing any error message to the user.

I eventally figured it out by cloning the repo and running the code

```
  ➜  Local:   http://localhost:1420/
  ➜  Network: use --host to expose
        Info Watching C:\Users\Ransom\repos\lrcget\src-tauri for changes...
   Compiling lrcget v0.5.0 (C:\Users\Ransom\repos\lrcget\src-tauri)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 4.22s
Database file path: C:\Users\Ransom\AppData\Roaming\net.lrclib.lrcget\db.sqlite3
Existing database version: 4
thread 'main' panicked at src/main.rs:450:34:
Failed to initialize audio player: Cannot find the default audio output device
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1202/150041.099:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 1412
```

but this should either:
- Let the user continue without an audio device
- Show the user an error so they can enable a device to fix the issue

**Comment by WinnerWind** [comment]
Hi there!
I'm having this issue on Arch Linux too, version 0.5.0
```
lrcget 

** (lrcget:28351): WARNING **: 18:27:22.822: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
Database file path: /home/soham/.local/share/net.lrclib.lrcget/db.sqlite3
Existing database version: 4
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
thread 'main' panicked at src/main.rs:450:34:
Failed to initialize audio player: The requested device is no longer available. For example, it has been unplugged.

Caused by:
    The requested device is no longer available. For example, it has been unplugged.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
It's quite annoying because I tried poking at the source too and couldn't figure out what to do.

**Comment by tranxuanthang** [comment]
> It's quite annoying because I tried poking at the source too and couldn't figure out what to do.

@WinnerWind Sorry for the late reply! The issue should be in this part of the code:

https://github.com/tranxuanthang/lrcget/blob/bcf72ee04d635bcd5a21dfeaaeda0767b4c6d93c/src-tauri/src/main.rs#L490

Instead of using `expect()`, which causes a panic if `Player::new()` fails, we could handle this more gracefully. For example, we could show a modal dialog in the UI to inform the user and allow them to retry initializing the player with `Player::new()` later.

**Comment by twistios** [comment]
I have a similar problem with LRCGET 0.9.3 AppImage-version (from Jan 2024-01-24) on Kubuntu 24.04.

```
Database file path: /home/user/.local/share/net.lrclib.lrcget/db.sqlite3
Existing database version: 6
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
thread 'main' panicked at src/main.rs:709:40:
Failed to initialize audio player: The requested device is no longer available. For example, it has been unplugged.
```

**Comment by WinnerWind** [comment]
I feel like at this point, there should be a modal dialogue implemented that shows a user-facing error message when the audio player is not available, or maybe it should have an option to boot without the audio player (Frankly i do not listen to music in LRCGet)
