### ISSUE TITLE
Embedding lyrics in file metadata

### ISSUE THREAD

**Issue by Batwam** [tranxuanthang/lrcget#75]
Hello,

My understanding is that LRCGET currently only allows to save the lyrics as .lrc files. Is there any plan to enable saving to the file metadata directly? Apologies if this has been discussed but I couldn't find any related discussion. 

Some apps like Navidrome only recognise embedded lyrics and having the data in the file makes sure it remains accessible even if the file is renamed. While people can write scripts to load the lyrics into the metadata, it would be neat if LRCGET had an option to either save as lrc or save as metadata?

**Comment by tranxuanthang** [comment]
This is actually on my TODO list, I just haven't had enough effort to implement it yet. It is a bit more complicated than it looks. I need some time to research how to embed the lyrics into each kind of file formats.

Also, embedding lyrics into the music files means mutating it, meaning there is a chance that the software corrupts the music files. Since there are some people run LRCGET on their huge (and probably valuable) music collection, we must implement this carefully.

**Comment by VeksCZ** [comment]
I will be glad if it start by working with mp3s. :) I had multiple backups, so I will gladly test some nightly for you.

**Comment by Batwam** [comment]
I'm currently using beets for this as the lyrics.py plugin now allows LRCLIB. Not sure how they implemented it but it's working nicely, just in case you are looking for inspiration.

**Comment by Dylancyclone** [comment]
I've also written a plugin for MusicBrainz Picard that grabs lyrics from LRCLIB and embeds them

https://gist.github.com/Dylancyclone/72fdb3515ed6b4150365c46fe07f4de8

**Comment by Batwam** [comment]
By the way, if you are looking to implement this, I would recommend to keep embedding as an option as some apps like Plex don't currently recognise embedded lyrics so this method may not work for everyone.

**Comment by VeksCZ** [comment]
> By the way, if you are looking to implement this, I would recommend to keep embedding as an option as some apps like Plex don't currently recognise embedded lyrics so this method may not work for everyone.

I have installed beet with lyrics plugin and I start to learn with that. I have created database. But I don't want to reorganize my library, just download .lrc & embed lyrics to mp3 tag. If I turn off copying whole library, lyrics plugin fetches lyrics but I can't see .lrc files anywhere nor lyrics embedded inside mp3 file itself. Can you help a little? Thank you.

**Comment by Batwam** [comment]
I'll respond on the part that's common for beets/lrcget as this is the lrcget repo so I'm assuming that you have all apps/plugins set up correctly. If not, I'd recommend posting on the beets issues tracker.

The issue could be that the lyrics don't exist in the database or the metadata isn't formatted properly. I'd recommend doing it on a file you know has lyrics available from [lrclib.net](https://lrclib.net/). If I remember correctly, the API requires not only the song/artist but also for the song duration to be close to the one in the database. Here is an example of a manual check you could do on LrcLib for [Idioteque](https://lrclib.net/api/get?artist_name=Radiohead&track_name=Idioteque&album_name=Kid%20A&duration=309). Get the artist/album/track/duration for the mp3 you are testing with and see if it returns anything.

**Comment by VeksCZ** [comment]
> Good news here, the embedding lyrics feature has been added in this commit:
> 
> [1ce9c7b](https://github.com/tranxuanthang/lrcget/commit/1ce9c7b75ff41862f3727ec7769a314b3a6ffce0)
> 
> It works for both MP3 and FLAC files. I’ve tested it on my library and haven’t encountered any issues so far, but I’ll run some more tests before making a release.

So if I want to test it I should download .main branch and build it?.
Thanks.

**Comment by tranxuanthang** [comment]
@VeksCZ yeah, the feature is there in the `main` branch.

**Comment by VeksCZ** [comment]
Some info from testing:

==> Scanning tracks take: 6568ms
thread 'tokio-runtime-worker' panicked at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\str\mod.rs:659:21:
byte index 30 is not a char boundary; it is inside 'á' (bytes 29..31) of `Budu vechno co si bude prát`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

My testing library was stuck on 155/1821 tracks at first try. The second try:

Cannot parse the tag info from track: `B:\Moje\Hudba\0 2 Oldies\9 9 Obřad\22 Tones & I - Dance Monkey (Street Violin Performance).mp3`. Error: `Encountered an invalid timestamp: Expected a separator`
==> Scanning tracks take: 5957ms
thread 'tokio-runtime-worker' panicked at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\str\mod.rs:659:21:
byte index 30 is not a char boundary; it is inside 'á' (bytes 29..31) of `Budu vechno co si bude prát`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I am from Czechia so we have a lot of unusual characters in track names.


And one warning when building:
warning: profile package spec `symphonia-format-wav` in profile `dev` did not match any packages. Did you mean `symphonia-format-caf`?

**Comment by tranxuanthang** [comment]
@VeksCZ Interesting, I will look into this bug as soon as I can.

> I can see Unsynced lyrics tag inside mp3 at tracks where there were lyrics found and the .lrc file is present.
> But what I would like to see lyrics inside Synced lyrics tag with timestamps. It is less useful than .lrc without that.

It does actually insert a SYLT tag (for synchronized lyrics) in MP3 files, you can test it with something like MusicBee in order to see it. I don't know why you don't see the SYLT tag, but keep in mind that SYLT tag is not very well supported among music players.

**Comment by tranxuanthang** [comment]
@VeksCZ,

```
thread 'tokio-runtime-worker' panicked at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\str\mod.rs:659:21:
byte index 30 is not a char boundary; it is inside 'á' (bytes 29..31) of `Budu vechno co si bude prát`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is weird, I can't reproduce similar issue even with a similar track (title: `Budu Všechno, Co Si Budeš Přát`).

Can I ask which Rust version you used to compile the source code?

Also, can you try to build the 0.4.0 tagged commit (https://github.com/tranxuanthang/lrcget/commit/a6af3d7f5493dc09abe1920a4ab594233e63981e) to check if you face a similar error?

**Comment by VeksCZ** [comment]
Maybe I am doing something not right.
I am running on Windows 11 with Webstorm, via  npm run tauri dev
rustc 1.81.0 (eeb90cda1 2024-09-04)

And it happens when I am downloading, scan is fine.

**Comment by tranxuanthang** [comment]
This feature is added in [v0.5.0](https://github.com/tranxuanthang/lrcget/releases/tag/0.5.0).

@VeksCZ Can you help me check if your problem still presents in the release build?

**Comment by VeksCZ** [comment]
Sorry, I had no time to test it until now. I have tried it on 500+ tracks and with exact those two mp3 which gave me error before and now everything looks good. No error at all.
I am using mp3tag editor and I have found out that it does not work with SYLT tag at all. Nor VirtualDJ. But for now it is great to have Synced lyrics inside mp3 for MusicBee and others.
Thank you for your work. I will send some coffee.

**Comment by tranxuanthang** [comment]
@VeksCZ I see. If you have some time, could you try running the development build with `RUST_BACKTRACE=1` to see if it shows the error belongs to which part or library?

```
RUST_BACKTRACE=1 npm run tauri dev
```

**Comment by VeksCZ** [comment]
Sorry, it took me some time. Error still persists. Rust Backtrace shows this:

thread 'tokio-runtime-worker' panicked at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\str\mod.rs:639:21:
byte index 30 is not a char boundary; it is inside '\u{82}' (bytes 29..31) of `AdrenalÃÂÃÂÃÂÃÂ­n`
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:662
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:74
   2: core::str::slice_error_fail_rt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\str\mod.rs:111
   3: core::str::slice_error_fail
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\str\mod.rs:68
   4: core::str::impl$0::split_at

**Comment by VeksCZ** [comment]
@tranxuanthang problem still persists with 0.9.0
![obrazek](https://github.com/user-attachments/assets/d2efb20b-8f21-477d-a891-51f9a341460c)

**Comment by KintsugiUwU** [comment]
Does it embed in ALAC (m4a) too or only FLAC?
